# -*- coding: utf-8 -*-
"""edge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18kDIz8tUhG_8Eaota1ExGJYlaLPlswjW
"""

from google.colab import files
from IPython.display import Image
from google.colab.patches import cv2_imshow
import cv2 
import numpy as np 
import matplotlib.pyplot as plt

image = cv2.imread("/content/beker.jpg", 1) 
edges = cv2.Canny(image, 50, 50)

Titles =["Original",  "edge"] 
images =[image,edges] 
count = 2
  
for i in range(count): 
    plt.subplot(2, 2, i + 1) 
    plt.title(Titles[i]) 
    plt.imshow(images[i]) 
  
plt.show()