# -*- coding: utf-8 -*-
"""haar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jc4RUDCSEY1wARKp41MJyvps3DIqjHe8
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
from google.colab import files
from IPython.display import Image

image = cv2.imread("/content/aiswarya.jpg", 1)
face_detection= cv2.CascadeClassifier('/content/haarcascade_frontalface_default.xml.txt')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
faces = face_detection.detectMultiScale(gray_image, 1.3, 5)

for (x,y,w,h) in faces:
   face_image = cv2.rectangle(image,(x,y),(x+w, y+h),(255,0,0),3)

    
Titles =["haar"] 
images =[face_image] 
count = 1
  
for i in range(count): 
    plt.subplot(2, 2, i + 1) 
    plt.title(Titles[i]) 
    plt.imshow(images[i]) 
  
plt.show()