# -*- coding: utf-8 -*-
"""image resize fromdrive

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qg11RnZfLyaZaSZ_rHsjrEmwnFz_wm-G
"""

import cv2 as cv
import numpy as np 
import matplotlib.pyplot as plt

image = cv.imread("/content/beker.jpg", 1)

half = cv.resize(image, (0, 0), fx = 0.1, fy = 0.1) 
bigger = cv.resize(image, (1050, 1610)) 
  
stretch_near = cv.resize(image, (780, 540)) 
    
Titles =["Original", "Half", "Bigger", "Interpolation Nearest"] 
images =[image, half, bigger, stretch_near] 
count = 4
  
for i in range(count): 
    plt.subplot(2, 2, i + 1) 
    plt.title(Titles[i]) 
    plt.imshow(images[i]) 
  
plt.show()